# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/user
Accept: application/json

###
GET http://localhost:8080/user/view/1
Accept: application/json

###
###
POST http://localhost:8080/user/abc
Content-Type: application/json

{
    "id": "4",
    "name": "user4",
    "email": "user444@dgsw"
}

###
PUT http://localhost:8080/user/put
Content-Type: application/json

{
    "id": "1",
    "name": "user1",
    "email": "11111@dgsw"
}

###
DELETE http://localhost:8080/user/delete/1

###